# Fabric Network Configuration

fabric.channel=mychannel
fabric.chaincode=contributioncontract

# Identity

fabric.user=admin

# Paths

fabric.wallet=resources/wallet
fabric.connection.profile=resources/connection-profile.yaml
